[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.20.0"

# Configure secrets scanning
[build.processing]
  skip_processing = false

# Allow Supabase environment variables in build output
[build.processing.secrets]
  # These are public environment variables that are safe to include in build
  omit_keys = ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"]
  
# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }
